apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: proxy-protocol-shim
data:
  HTTPS_UPSTREAM: UPSTREAM-NOT-SET.
  HTTP_UPSTREAM: UPSTREAM-NOT-SET.
  haproxy.cfg: |
    global
    	log stdout format raw local0
    	stats timeout 30s
    	user haproxy
    	group haproxy
    
    defaults
    	log	global
    	mode	tcp
    	option	tcplog
    	option	dontlognull
        balance source
        timeout connect 5000
        timeout client  50000
        timeout server  50000
    
    frontend http80
        bind *:80
        mode http
        http-request redirect scheme https
    
    frontend https443
        bind *:443
        default_backend httpsnodes
    
    backend httpnodes
        server s1 $HTTP_UPSTREAM check send-proxy
    
    backend httpsnodes
        server s1 $HTTPS_UPSTREAM check send-proxy
    
    frontend stats
        mode http
        option httplog
        bind *:8404
        stats enable
        stats uri /
        stats refresh 10s
        stats admin if LOCALHOST

