apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: proxy-protocol-shim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shim
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shim
    spec:
      containers:
       -  image: haproxy:latest
          name: haproxy
          env:
          - name: HTTP_UPSTREAM
            valueFrom:
              configMapKeyRef:
                name: haproxy
                key: HTTP_UPSTREAM
          - name: HTTPS_UPSTREAM
            valueFrom:
              configMapKeyRef:
                name: haproxy
                key: HTTPS_UPSTREAM
          volumeMounts:
            - mountPath: /usr/local/etc/haproxy/haproxy.cfg
              name: config
              subPath: haproxy.cfg
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 8404
            name: stats
            protocol: TCP
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: haproxy
