apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: proxy-protocol-shim
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: http
  - name: https-443
    port: 443
    protocol: TCP
    targetPort: https
  - name: https-8404
    port: 8404
    protocol: TCP
    targetPort: stats
  selector:
    app: shim
  type: LoadBalancer
